my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),

    # "article"模块的：url访问路径
    path("article/",include("article.urls",namespace="article")),
    # "userprofile"用户管理模块的：url访问路径
    path("userprofile/",include("userprofile.urls",namespace="userprofile")),
    # 第3方app："Django-password-reset"(重置密码)
    path("password-reset/",include("password_reset.urls")),
    # "comment"：评论模块的url
    path("comment/",include("comment.urls",namespace="comment")),

    # 评论的：消息通知 ——————————————————注意：不再是字符串，为确保模块，安装到正确的namespace中！
    path("inbox/notifications/",include(notifications.urls,namespace="notifications")),

    # 消息通知app：集中处理"已读/未读"
    path("notice/",include("notice.urls",namespace="notice")),

    # 添加第3方app："django-allauth库"，实现blog第三方登录！
    path("accounts/",include("allauth.urls")),
]

# 处理MEDIAL_URL中的：媒体文件，如Profile()中，用户头像"avatar"
from django.conf import settings
from django.conf.urls.static import static
# 这样：就为以后上传的图片，配置好了url路径
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# 设置blog网站"首页"
from article.views import article_list
urlpatterns += [
    path("",article_list,name="home"),
]

my_blog/notice/urls.py
from django.urls import path
from . import views

app_name = "notice"

urlpatterns = [
    # 通知列表
    path("list/",views.CommentNoticeListView.as_view(),name="list"),
    # 更新通知状态
    path("update/",views.CommentNoticeUpdateView.as_view(),name="update"),
]

# 注意：path()的参数2，只能接收1个函数，不要直接写"类名"，因此要调类试图的"as_views()"方法！

my_blog/userprofile/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名字"app_name="，Django2中必须写上！
app_name = "userprofile"

urlpatterns = [
    # 用户"登录"
    path("login/",views.user_login,name="login"),
    # 用户"登出"
    path("logout/",views.user_logout,name="logout"),
    # 用户"注册"
    path("register/",views.user_register,name="register"),
    # 用户"删除"
    path("delete/<int:id>/",views.user_delete,name="delete"),
    # 用户信息：
    path("edit/<int:id>/",views.profile_edit,name="edit"),
]

my_blog/userprofile/models.py
from django.db import models


# Create your models here.
# 扩展"用户信息"：自带的User模型，字段少的可怜，添上"电话号、头像"(用模型"1对1关联"的方法)

from django.contrib.auth.models import User
# 引入：内置信号"post_save"
# from django.db.models.signals import post_save ——————信号实现"User和Profile"同步创建的"bug修复"
# 引入：信号接收器receiver的"装饰器"
# from django.dispatch import receiver


# 扩展：用户信息
class Profile(models.Model):
    # 与User模型：构成"1对1"关联                                # 反向操作时的字段名，代替"_set"
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    # 电话号
    phone = models.CharField(max_length=20,blank=True)
    # 头像："%Y%m%d"是日期格式化的写法，最终格式化为"系统时间"
    avatar = models.ImageField(upload_to="avatar/%Y%m%d",blank=True)
    # 个人简介
    bio = models.TextField(max_length=500,blank=True)
    # blank和null的区别：null是数据库的范围，而blank是用于验证。若1个字段的blank=True,
    # Django进行表单数据验证时，会允许该字段是空值。

    def __str__(self):
        return "user {}".format(self.user.username)


# 信号接收函数(信号,sender=发送者)：——————新建User实例时，会自动调用！
# @receiver(post_save,sender=User)
# def create_user_profile(sender,instance,created,**kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# # 信号接收函数：——————更新User实例时，会自动调用！
# @receiver(post_save,sender=User)
# def save_user_profile(sender,instance,**kwargs):
#     instance.profile.save()

# Django的信号机制："sender-->post_save信号-->receiver"，这里当模型调用.save()方法保存入库后触发
# 接收函数()：实现了每当"User"创建/更新时，发送"信号"启动def()函数，使"Profile"也自动的创建/更新。
# 为什么：删除User表不需要信号？
# 答案是：两者的关系采用了models.CASCADE级联删除，已经带有关联删除的功能了。
# 当然：可以不使用信号来自动创建Profile()表，而采用手动方式实现。


# 注意：建好做makemigrations-migraet后，还不能直接admin登录"lenovo"，会报错！！！
# 因为：之前建的User数据都没有对应的Profile模型，违背了现有的模型。
# 1种解决办法：是干脆删除旧的数据，因此就需用到Django的shell命令。——————：python manage.py shell进入shell！
# shell下>>>：删除User数据库，此时级联的article模型库也会删除，相关文章也没了！
# 命令：from django.contrib.auth.models import User、User.objects.all().delete()
# 此时：再"select * from auth_user/article；——————：=Empty set (0.00 sec)"为空！
# 删完：重新"createsuperuser"，建管理员账户。

# BUG修复：信号实现"User和Profile"同步创建，会产生bug，因此注释掉！！！

my_blog/userprofile/forms.py
# 用户登录：需填写的账号密码表单数据

# 引入：forms表单类
from django import forms
# 引入：内置的User模型
from django.contrib.auth.models import User


# 用户：登录表单
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 用户：注册表单
class UserRegisterForm(forms.ModelForm):
    # 覆写掉：User的"password"字段，以便我们自己进行数据的验证工作
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        # 继承的User模型中的password字段就没了，已经被上面覆写掉了！
        fields = ["username","email"]

    # 对2次密码：是否一致进行检查
    # def clean_[字段]：这种写法Django会自动调用，来对单个字段的数据进行验证清洗。
    def clean_password2(self):
        data = self.cleaned_data
        if data.get("password") == data.get("password2"):
            return data.get("password")
        else:
            raise forms.ValidationError("两次输入不一致，请重试！")


# 注意：这里是"clean_password2()"，不然会导致password2被Django判定为无效数据而清洗掉，
# 从而password2属性不存在。最终导致两次密码输入始终会不一致，并且很难判断出错误原因。

# 自定义验证：Django中使用"def clean()"方法，对表单中的数据进行验证。(对某个字段，进行自定义的验证)
# 方式：定义1个方法，方法名规则是"clean_fieldname"，若验证失败，就抛出1个验证错误"ValidationError()"。
# 若需要针对多个字段进行验证，那么可以重写 clean 方法


from .models import Profile  # 引入：Profile模型


# 扩展：用户信息的"表单类"
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["phone","avatar","bio"]

my_blog/userprofile/views.py
from django.shortcuts import render,redirect

# Create your views here.
# 用户管理：登录、退出、注册、删除

# 导入：Django自带的登录验证模块
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from .forms import UserLoginForm,UserRegisterForm


# 用户登录：
def user_login(request):
    if request.method == "POST":
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            # 检验：账号-密码是否正确，匹配数据库中的已有用户 (匹配到就返回该user对象)
            user = authenticate(username=data["username"],password=data["password"])
            if user:
                # 登录：并将数据存在session中，绑定当前的"request"和"user"
                login(request,user)
                # 登录后，返回到文章"列表页"
                return redirect("article:article_list")
            # 无user：为"空"，
            else:
                return HttpResponse("账号或密码输入有误，请重新输入！")
        else:
            return HttpResponse("账号或密码输入不合法！(与登录表单类不符合)")
    elif request.method == "GET":
        user_login_form = UserLoginForm()
        context = {"form":user_login_form}
        return render(request,"userprofile/login.html",context)
    else:
        return HttpResponse("请使用'GET/POST'请求数据！")


# 用户退出(登出)：也用Django自带的，直接auth的第3个兄弟"auth.logout()"
def user_logout(request):
    logout(request)
    return redirect("article:article_list")


# 用户注册：
def user_register(request):
    if request.method == "POST":
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置：密码
            new_user.set_password(user_register_form.cleaned_data["password"])
            # 保存数据
            new_user.save()
            # 注册成功后，登录。
            login(request,new_user)
            # 返回到博客"列表页"。
            return redirect("article:article_list")
        else:
            return HttpResponse("注册表单有误，请重新输入！")
    elif request.method == "GET":
        user_register_form = UserRegisterForm()
        context = {"form":user_register_form}
        return render(request,"userprofile/register.html",context)
    else:
        return HttpResponse("请使用'GET/POST'请求数据")


from django.contrib.auth.models import User
# 引入：验证登录的"装饰器"
from django.contrib.auth.decorators import login_required

# 用户删除：前提"必须是登录用户、且是本用户" ——————安全！！
# 装饰器：要求调用user_delete()函数时，用户必须已登录；
# 若未登录则不执行此函数，将页面重定向到"/userprofile/login/"地址去。
@login_required(login_url="/userprofile/login/")
def user_delete(request,id):
    if request.method == "POST":
        user = User.objects.get(id=id)
        # 验证：删除操作的人，是否是当前登录的用户本人
        if request.user == user:
            # 是本人：退出登录、删除数据
            logout(request)
            user.delete()
            # 返回：到博客文章"列表页"
            return redirect("article:article_list")
        else:
            return HttpResponse("抱歉：您没有删除操作的权限！")
    else:
        return HttpResponse("仅接受post请求！")


from .forms import ProfileForm
from .models import Profile

# 编辑：用户信息 ——————：# 未登录不执行此函数，将页面重定向到"/userprofile/login/"地址去。
@login_required(login_url='/userprofile/login/')
def profile_edit(request,id):
    user = User.objects.get(id=id)
    # user_id：是外键自动生的字段，表两个表的关联
    # profile = Profile.objects.get(user_id=id) ——————注释：掉旧代码！

    # 修改：让"Profile表"根据是否已经存在，而动态的创建、获取
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:  # 不存在，就创建
        profile = Profile.objects.create(user=user)  # 见Django-orm的增加数据操作！

    if request.method == "POST":
        # 验证：修改数据者，是否为本人
        if request.user != user:
            return HttpResponse("亲,你无权限修改此用户信息哦！")

        # 上传的头像文件：是存在"request.FILES"中，参数传递给表单类
        profile_form = ProfileForm(request.POST,request.FILES)  # 修改本行：上传的用户头像处理
        if profile_form.is_valid():
            # 取出：清洗后的数据
            profile_cd = profile_form.cleaned_data
            # 重新：编辑赋值，保存进数据库
            profile.phone = profile_cd["phone"]
            profile.bio = profile_cd["bio"]
            # 若：request.FILES中有头像文件，则赋值保存
            if "avatar" in request.FILES:
                profile.avatar = profile_cd["avatar"]
            profile.save()
            # 返回到，修改后的"编辑页"
            return redirect("userprofile:edit",id=id)
        else:
            return HttpResponse("注册表单输入有误，请重新输入~")
    elif request.method == "GET":
        context = {"user":user,"profile":profile}
        return render(request,"userprofile/edit.html",context)
    else:
        return HttpResponse("亲,请使用get/post请求数据！")

# request.FILES属性：表单上传的文件对象，是存储在类字典对象request.FILES中的，因此要修改表单类参数，将它也传入进去！

my_blog/templates/userprofile/edit.html
<!DOCTYPE html>

<html lang="en">
<head>
    {% extends "base.html" %}
    {% load static %}
    <meta charset="UTF-8">
    {% block title %}用户信息{% endblock %}
</head>

<body>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <div class="col-md-4">用户名：{{ user.username }}</div>
                <br>
                <!-- 添加：上传用户头像处理 -->
                {% if profile.avatar %}
                    <div class="col-md-4">头像</div>
                    <!--有头像：就"最大宽度20%,圆角边"显示-->
                    <img src="{{ profile.avatar.url }}" style="max-width:20%;border-radius:15%;" class="col-md-4">
                {% else %}
                    <h5 class="col-md-4">暂无头像</h5>
                {% endif %}

                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- avatar:头像 -->
                    <div class="form-group col-md-4">
                        <label for="avatar">上传头像</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>
                    <!-- phone:电话 -->
                    <div class="form-group col-md-4">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                    </div>
                    <!-- bio:简介 -->
                    <div class="form-group col-md-4">
                        <label for="bio">简介</label>
                        <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

my_blog/templates/userprofile/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}
    {% load static %}
    <meta charset="UTF-8">
    {% block title %}登录{% endblock %}

</head>

<body>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <!--注册入口：添加到此处即可-->
                <p>用已有本地账号或<a href="{% url 'userprofile:register' %}">注册</a>新账号。也可通过第三方登录：</p>
                <div class="socialaccount_ballot">
                    <h5 class="mb-2 mt-4">第三方登录：</h5>
                    <ul class="socialaccount_providers">
                        {% include "socialaccount/snippets/provider_list.html" with process="login" %}
                    </ul>
                    <h5 class="mb-2 mt-4">本地登录：</h5>
                </div>

                <!--登录(本地)：-->
                <div class="col-6">
                    <form method="post" action=".">
                        {% csrf_token %}
                        <!-- 账号 -->
                        <div class="form-group">
                            <label for="username">账号：</label>
                            <!--name：指定的控件提交数据的名称，必须与登录forms.py中的fields字段名对应-->
                            <input type="text" id="username" name="username" class="form-control" placeholder="请输入用户名/Email" autofocus="autofocus" required>
                            <small class="form-text text-muted ml-1">
                                还没有账号？<a href="{% url 'userprofile:register' %}" style="color:cornflowerblue;">注册新账号</a>
                            </small>
                        </div>
                        <!-- 密码 -->
                        <div class="form-group">
                            <label for="password">密码：</label>
                            <input type="password" name="password" id="password" class="form-control" placeholder="请输入密码" required>
                            <small class="form-text text-muted ml-1">
                                忘记密码？点击<a href="{% url 'password_reset_recover' %}">这里</a>重置密码
                            </small>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary">确认</button>
                    </form>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

my_blog/templates/userprofile/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}
    {% load static %}
    <meta charset="UTF-8">
    {% block title %}登录{% endblock %}
</head>
<body>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- 账号-->
                    <div class="form-group col-md-4">
                        <label for="username">昵称</label>
                        <!--input表单元素：required属性，是HTML5中的新属性。-->
                        <!--required属性：规定在提交表单前，必需填写输入字段。不填写，表单就不能提交，并提示用户填写-->
                        <input type="text" placeholder="如'张三'" class="form-control" id="username" name="username" required>
                    </div>
                    <!-- 邮箱 -->
                    <div class="form-group col-md-4">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group col-md-4">
                        <label for="password">设置密码</label>
                        <input type="password" placeholder="密码设置为4-8位(字母/数字)" class="form-control" id="password" name="password" required>
                    </div>
                    <!-- 确认密码 -->
                    <div class="form-group col-md-4">
                        <label for="password2">确认密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

my_blog/templates/userprofile/zbb.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}
    {% load static %}
    <meta charset="UTF-8">
    {% block title %}登录{% endblock %}

</head>

<body>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <!--注册入口：添加到此处即可-->
                <h5>亲,还没账号？</h5>
                <h5>点击<a href="{% url 'userprofile:register' %}">注册账号</a>加入我们吧！</h5>
                <br>

                <!--登录(本地)：-->
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group">
                        <label for="username">账号</label>
                        <!--name：指定的控件提交数据的名称，必须与登录forms.py中的fields字段名对应-->
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>

                <!--新增："重置密码"app的入口-->
                <br>
                <h5>亲,忘记密码？</h5>
                <h5>点击<a href="{% url 'password_reset_recover' %}">这里</a>重置密码</h5>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>