my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),

    # "article"模块的：url访问路径
    path("article/",include("article.urls",namespace="article")),
    # "userprofile"用户管理模块的：url访问路径
    path("userprofile/",include("userprofile.urls",namespace="userprofile")),
    # 第3方app："Django-password-reset"(重置密码)
    path("password-reset/",include("password_reset.urls")),
    # "comment"：评论模块的url
    path("comment/",include("comment.urls",namespace="comment")),

    # 评论的：消息通知 ——————————————————注意：不再是字符串，为确保模块，安装到正确的namespace中！
    path("inbox/notifications/",include(notifications.urls,namespace="notifications")),

    # 消息通知app：集中处理"已读/未读"
    path("notice/",include("notice.urls",namespace="notice")),

    # 添加第3方app："django-allauth库"，实现blog第三方登录！
    path("accounts/",include("allauth.urls")),
]

# 处理MEDIAL_URL中的：媒体文件，如Profile()中，用户头像"avatar"
from django.conf import settings
from django.conf.urls.static import static
# 这样：就为以后上传的图片，配置好了url路径
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# 设置blog网站"首页"
from article.views import article_list
urlpatterns += [
    path("",article_list,name="home"),
]

my_blog/notice/urls.py
from django.urls import path
from . import views

app_name = "notice"

urlpatterns = [
    # 通知列表
    path("list/",views.CommentNoticeListView.as_view(),name="list"),
    # 更新通知状态
    path("update/",views.CommentNoticeUpdateView.as_view(),name="update"),
]

# 注意：path()的参数2，只能接收1个函数，不要直接写"类名"，因此要调类试图的"as_views()"方法！

my_blog/notice/models.py
from django.db import models

# Create your models here.

my_blog/notice/views.py
from django.shortcuts import render,redirect

# Create your views here.
# 这里：我们学习使用"类视图"写法，不采用传统的"视图函数"！！！(具体看Django文档)

from article.models import ArticlePost
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


# 通知列表                # 继承"混入类Mixin"：要求调此视图必"先登录"！
class CommentNoticeListView(LoginRequiredMixin,ListView):
    # 上下文名称
    context_object_name = "notices"
    # 模板的位置
    template_name = "notice/list.html"
    # 登录重定项
    login_url = "/userprofile/login/"

    # 未读通知的"查询集"：覆写"get_queryset()"方法，返回传给模板的"未读通知对象"！
    def get_queryset(self):
        return self.request.user.notifications.unread()

# 混入类"Mixin"：指具有某些功能、通常不独立使用、提供给其他类继承功能的类。就是“混入”的意思。


# 更新：通知状态
class CommentNoticeUpdateView(View):
    # 处理get请求
    def get(self,request):
        # 获取：未读消息
        notice_id = request.GET.get("notice_id")
        # 更新：单条通知
        if notice_id:
            article = ArticlePost.objects.get(id=request.GET.get("article_id"))
            request.user.notifications.get(id=notice_id).mark_as_read()

            # 参数是model对象时,会自动调model的"get_absolute_url()方法"注意：和重定url的原理一样，只是这里"换种"实现方式！
            return redirect(article)
        # 更新：全部通知
        else:
            request.user.notifications.mark_all_as_read()
            return redirect("notice:list")

# mark_as_read()/all_as_read()：是notifications模块提供的方法，用于将未读通知转换为"已读"！

my_blog/templates/notice/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}
    {% load static %}
    <meta charset="UTF-8">
    {% block title %}
        消息通知
    {% endblock title %}
</head>
<body>
{% block content %}
<div class="container">
    <div class="row mt-4 ml-4">
        <!--a1：清空所有通知-->
        <a href="{% url 'notice:update' %}" class="btn btn-warning" role="button">清空所有通知</a>
    </div>
    <!-- 未读通知列表："lenovo在xxx回复了你。 2020/01/11 11:13" -->
    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice in notices %}
                <li class="list-group-item" id="notice_link">
                    <!--a2：点击单个通知，标记为已读，并前往评论所在的文章！-->
                    <!--新增：评论通知的"锚点"，comment_elem_{{notice.action.object.id}}-->
                    <a href="{% url 'notice:update' %}?article_id={{ notice.target.id }}&notice_id={{ notice.id }}#comment_elem_{{ notice.action_object.id }}" target="_blank">
                        <span style="color:#5897fb;">
                            {{ notice.actor }}
                        </span>
                            在<span style="color:#01a252;">{{ notice.target }}</span> {{ notice.verb }}。
                    </a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp{{ notice.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<!--伪类选择器：将已经点击过的"通知"，字体颜色转为"浅灰色"-->
<style>
    /*访问前":link"(a默认蓝色文本+下划线)*/
    #notice_link a:link{
        color:black;
    }
    /*访问后":visited"*/
    #notice_link a:visited{
        color:lightgrey;
    }
</style>
{% endblock%}
</body>
</html>