my_blog/article/urls.py
from django.urls import path

from . import views

# 正在部署的应用的名字"app_name="，Django2中必须写上！
app_name = "article"

urlpatterns = [
    # 文章列表页
    path("article-list/",views.article_list,name="article_list"),
    # 文章详情 (Django2：path的新语法，类似"flask"的带参数的路由)
    path("article-detail/<int:id>/",views.article_detail,name="article_detail"),
    # Forms：写文章
    path("article-create/",views.article_create,name="article_create"),
    # 删除文章
    # path("article-delete/<int:id>/",views.article_delete,name="article_delete"),
    # post防csrf攻击：安全删除文章
    path("article-safe-delete/<int:id>/",views.article_safe_delete,name="article_safe_delete"),
    # 修改：更新文章
    path("article-update/<int:id>/",views.article_update,name="article_update"),

    # 点赞+1
    path("increase-likes/<int:id>/",views.IncreaseLikesView.as_view(),name="increase_likes"),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),

    # "article"模块的：url访问路径
    path("article/",include("article.urls",namespace="article")),
    # "userprofile"用户管理模块的：url访问路径
    path("userprofile/",include("userprofile.urls",namespace="userprofile")),
    # 第3方app："Django-password-reset"(重置密码)
    path("password-reset/",include("password_reset.urls")),
    # "comment"：评论模块的url
    path("comment/",include("comment.urls",namespace="comment")),

    # 评论的：消息通知 ——————————————————注意：不再是字符串，为确保模块，安装到正确的namespace中！
    path("inbox/notifications/",include(notifications.urls,namespace="notifications")),

    # 消息通知app：集中处理"已读/未读"
    path("notice/",include("notice.urls",namespace="notice")),

    # 添加第3方app："django-allauth库"，实现blog第三方登录！
    path("accounts/",include("allauth.urls")),
]

# 处理MEDIAL_URL中的：媒体文件，如Profile()中，用户头像"avatar"
from django.conf import settings
from django.conf.urls.static import static
# 这样：就为以后上传的图片，配置好了url路径
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# 设置blog网站"首页"
from article.views import article_list
urlpatterns += [
    path("",article_list,name="home"),
]

my_blog/notice/urls.py
from django.urls import path
from . import views

app_name = "notice"

urlpatterns = [
    # 通知列表
    path("list/",views.CommentNoticeListView.as_view(),name="list"),
    # 更新通知状态
    path("update/",views.CommentNoticeUpdateView.as_view(),name="update"),
]

# 注意：path()的参数2，只能接收1个函数，不要直接写"类名"，因此要调类试图的"as_views()"方法！

my_blog/userprofile/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名字"app_name="，Django2中必须写上！
app_name = "userprofile"

urlpatterns = [
    # 用户"登录"
    path("login/",views.user_login,name="login"),
    # 用户"登出"
    path("logout/",views.user_logout,name="logout"),
    # 用户"注册"
    path("register/",views.user_register,name="register"),
    # 用户"删除"
    path("delete/<int:id>/",views.user_delete,name="delete"),
    # 用户信息：
    path("edit/<int:id>/",views.profile_edit,name="edit"),
]

my_blog/templates/back_to_top_func.html
<!--给文章"详情页"：增加1个回到顶部的"浮动按钮"，CSS的z-index属性设置元素的堆叠次序-->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index:100;"></button>

<!--向上滚动的Jquery函数-->
<script>

    //页面加载完后：监听"2个"事件
    $(function (){
        // 事件1：点击按钮时，将页面滚到顶部，0.5s完成滚动动作
        $("#BackTop").click(function (){
            $("html,body").animate({scrollTop:0},500);
        });
        // 事件2：页面滚动时，根据页面距离顶部的距离(是否>300px)，决定按钮的"显示/隐藏"
        $(window).scroll(function(){
            //>300px：则以0.3s的特效"显示"按钮
            if($(this).scrollTop()>300){
                $("#BackTop").fadeIn(300);
            }else{
                //否则：先停止正在进行的特效，接着以0.3s的特效"隐藏"按钮
                $("#BackTop").stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的"大小、位置、样式"设置 */
    /*rem：是CSS3新增的1个相对单位，用它为元素设定字体大小时，仍然是相对大小，但相对的只是HTML根元素。*/
    .toTop-arrow{
        width:3.5rem;   /*大小、内外边距、边框、边框圆角*/
        height:3.5rem;
        padding:0px;
        margin:0px;
        border:0px;
        border-radius:33%;
        opacity:0.7;       /*显示设置：透明度0.7*/
        background:black;  /*背景"简写"*/
        cursor:pointer;    /*光标显示："pointer"指针放上去显示"小手"！*/
        position:fixed;    /*定位布局：固定定位*/
        right:1.5rem;      /*偏移属性"右1.5，底1.5"*/
        bottom:1.5rem;
        display:none;      /*显示设置："none"元素隐藏，隐藏后"不占位"*/
    }
    /* 绘制：按钮中的"向上箭头"，运用"伪元素:before和:after",::before是CSS3中写法 */
    .toTop-arrow::before, .toTop-arrow::after{
        content:"";  /*不给为元素设置内容，仅作为容器，装"左右箭头"*/
        width:31px;
        height:7px;
        border-radius:3px;
        background:orange;
        position:absolute;  /*定位布局：绝对定位*/

    }
    .toTop-arrow::before{
        transform:rotate(-45deg) translate(0,-50%);  /*转换属性："rotate"旋转、"translate"平移*/
        left:0.4rem;  /*偏移属性"左0.4rem"*/
    }
    .toTop-arrow::after{
        transform:rotate(45deg) translate(0, -50%);
        right:0.4rem; /*偏移属性"右0.4rem"*/
    }
    /* 取消点击按钮时的"聚焦" */
    .toTop-arrow:focus{
        outline:none; /*outline轮廓线：位于边框边缘的外围，起到突出元素的作用。*/
    }
</style>

my_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <!-- 整个项目的"基础模板"：所有网页都继承它 -->
    <!--预留：网站标题title的位置-->
    <title>{% block title %}{% endblock  %}</title>

    <!-- jquery.js和popper.js，要在bootstrap.js前引入！！！-->
    <!--引入：bootstrap.js依赖的"jquery.js"和"popper.js"-->
    <script src="{% static 'jquery/jquery-3.5.1.js' %}"></script>
    <!--popper.js采用：cdn远程引入,未下载到本地(因版本兼容问题)-->
    <!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>-->
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!--引入：bootstrap的css文件-->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!--引入：bootstrap的js文件-->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!--引入：monokai.css文件(pygments的深色背景的代码高亮样式文件)-->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

    <!--引入：layer.js，"base中"增加这个"Layer组件",让所有页面都能使用弹窗提示功能！(它也依赖jquery.js，也要在其后引入)-->
    <script src="{% static 'layer/layer.js' %}"></script>
</head>

<body>
    <!--引入：导航栏-->
    {% include 'header.html' %}

    <!--新增：两个"div"容器，解决页脚取消"fixed-bottom"后，页脚沉底问题-->
    <div id="wrapper">
        <!--预留：具体页面的位置-->
        {% block content %}{% endblock %}
        <div id="push"></div>
    </div>
    <!--增加样式-->
    <style>
        /*控制页面：尺寸不小于屏幕的高度*/
        html,body{
            height:100%;
            margin:0px;
        }
        /*容器：底部有个负边距，给页脚让出60px位置*/
        #wrapper{
            min-height:100%;
            margin-bottom:-60px;
        }
        /*留出：一段与"页脚等高"的空隙，避免正文内容与页脚重叠*/
        #footer,#push{
            height:60px;
        }
    </style>

    <!--引入：注脚-->
    {% include 'footer.html' %}

    <!--引入：回到顶部的"浮动按钮"-->
    {% include "back_to_top_func.html" %}

    <!--pygments的.css表格样式太难看了，博主在页面中用Jquery动态加载了Bootstrap的表格样式，像这样-->
    <!--其实注释不写，也没啥影响！-->
    <!--<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>-->
    <!--<script>-->
        <!--$('div#article_body table').addClass('table table-bordered');-->
        <!--$('div#article_body thead').addClass('thead-light');-->
    <!--</script>-->
</body>
</html>

my_blog/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>注脚</title>
</head>

<body>
    <div>
        <br><br><br>
    </div>
    <!--删除："fixed-bottom"属性，防止层级太高，盖住浮动"按钮"！-->
    <!--新增：id='footer'属性-->
    <footer class="py-3 bg-dark" id="footer">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; www.zhangbinmyblog.com 2018-2021</p>
        </div>
    </footer>
    <!--footer:HTML5的新标签,表文档/部分区域的页脚,应包含的元素信息"如创者姓名/文档的日期/创者的联系信息等-->
</body>
</html>

my_blog/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>导航栏</title>

    <!--引入评论：消息通知，"django-notifications"自带的模板标签tags-->
    {% load notifications_tags %}
    <!--调用：通知相关的"对象"，如"unread_count"是当前用户的未读通知的计数 -->
    {% notifications_unread as unread_count %}

</head>

<body>
<!-- 定义：导航栏 -->
<!--nav：HTML5的新标签,定义导航链接的部分。只是用来表该区域是导航链接,并没什么显示效果,只起到语义的作用-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏：商标-->
        <a class="navvar-brand" href="{% url 'article:article_list' %}">个人博客</a>
        <!-- 导航：入口-->
        <div>
            <ul class="navbar-nav">
                <!--条目-->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                </li>

                <!--加入：登录按钮-->
                <!--is_authenticated：是models.User类的属性，用于判断用户是否已通过身份验证-->
                {% if user.is_authenticated %}
                    <!--若用户：已登录，则显示"用户名"的下拉框-->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <!--新增：评论消息通知"小红点" (因Bootstrap只要徽章的样式,这里用svg自己画了)-->
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8" width="8px" height="8px">
                                    <circle cx="4" cy="4" r="4" fill="#ff6b6b"></circle>
                                </svg>
                            {% endif %}

                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                            <!--新增："删除用户"-->
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <!--新增："用户信息"(入口)-->
                            <a class="dropdown-item" href="{% url 'userprofile:edit' user.id %}">个人信息</a>
                            <!--新增：消息通知"计数"入口-->
                            <a class="dropdown-item" href="{% url 'notice:list' %}">新通知
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                        </div>
                    </li>
                {% else %}
                    <!--若用户：未登录，则显示"登录"来提醒-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                    </li>
                {% endif %}

                <!--弹窗组件："删除用户"-->
                <!--添个隐藏表单：用"post"删除用户，防止csrf攻击误删除！(和删除文章同理)-->
                {% if user.is_authenticated %}
                    <form style="display:none;" id="user_delete"
                          action="{% url 'userprofile:delete' user.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                    <script>
                        function user_delete(){
                            //调用"layer"弹窗组件
                            layer.open({
                                title:"确认删除",
                                content:"亲，确定删除用户资料吗？",
                                //点击"确定"按钮后,调用回调函数
                                yes:function(index,layero){
                                    $("form#user_delete button").click();
                                },
                            })
                        }
                    </script>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

</body>
</html>

my_blog/templates/zbb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .c1{
            /*display: block;*/
            position:absolute;
            width:100px;
            height:160px;
            background-color:red;
            border-radius: 50px 50px 0 0;
        }
        .c1{
            background-color:red;
            transform-origin:right bottom;
            /*transform:rotate(45deg);*/
            top:50px;
            left:200px;
        }

    </style>
</head>
<body>
    <span class="c1">aaa</span>
</body>
</html>